source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

target 'BaixingSDK_Example', :exclusive => true do
  pod "BaixingSDK", :path => "../"
end

target 'BaixingSDK_Tests', :exclusive => true do
  pod "BaixingSDK", :path => "../"
end
