source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BaixingSDK_Example', :exclusive => true do
  pod "BaixingSDK", :path => "../"
  
  pod 'AFNetworking'
  pod 'FMDB'
end

target 'BaixingSDK_Tests', :exclusive => true do
  pod "BaixingSDK", :path => "../"

  pod 'FBSnapshotTestCase'
end
