source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

target 'BaixingSDK_Example' do
  pod "BaixingSDK", :path => "../"
end

target 'BaixingSDK_Tests' do
  pod "BaixingSDK", :path => "../"
end
